---
# Symlink docker bash completions

- name: Symlink docker.bash-completion
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion"
    dest: "/usr/local/etc/bash_completion.d/docker"
    state: link

- name: Symlink docker-machine.bash-completion
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion"
    dest: "/usr/local/etc/bash_completion.d/docker-machine"
    state: link

- name: Symlink docker-compose.bash-completion
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion"
    dest: "/usr/local/etc/bash_completion.d/docker-compose"
    state: link